### ISSUE TITLE
name_lookup habitat command

### ISSUE THREAD

**Issue by willgearty** [ropensci/rgbif#135]
I have been using the name_lookup command to determine whether a mammal species is marine using a command like:
`name_lookup(query="Vulpes lagopus", rank="species", higherTaxonKey=359, habitat=TRUE, return="data")`
I also check whether the species is non-marine using a command like:
`name_lookup(query="Vulpes lagopus", rank="species", higherTaxonKey=359, habitat=FALSE, return="data")`
When this style of data collection revealed that the artic fox (Vulpes lagopus) is marine and **not non-marine**, I was taken aback.
So, I looked up the artic fox (http://cdn.gbif.org/species/5219303) to see that GBIF has it coded as **"Terrestrial, Marine"** (as it should be, I suppose).
Then, just figuring why not, I tried the following command:
`name_lookup(query="Vulpes lagopus", rank="species", higherTaxonKey=359, habitat="Terrestrial", return="data")`
and the returned information contained the artic fox!
I had no idea that the habitat command had this type of flexibility (as the pdf and R help documentation both still have it listed as a boolean command).
Now that I know this, I can just use the text habitats for the command, but it may be good to somehow have FALSE grab "Not marine" and "Terrestrial" taxa.
Either way, it would also be great if the documentation could be updated, although I understand that would be a huge undertaking.
Thanks again for an amazing R package,
Will

**Comment by willgearty** [comment]
Hi Scott,
It appears the api backend for habitat has changed once again (or you changed something in the package?).
A normal lookup such as this:
```name_lookup(query="*", rank="species", higherTaxonKey=358,limit=1000,start=(1000*i))```
returns new columns X.TERRESTRIAL and X.MARINE instead of the previous "marine" column.

Additionally, the command from above that should now work:
```name_lookup(query="Vulpes lagopus", rank="species", higherTaxonKey=5219234, habitat=FALSE, return="data")```
results in an error now:
```Error: is.logical(x) || is.null(x) is not TRUE```

On the website, it seems they have changed from boolean values to strings, as this works:
http://api.gbif.org/v1/species/search?highertaxonKey=359&habitat=terrestrial
but this doesn't:
http://api.gbif.org/v1/species/search?highertaxonKey=359&habitat=true

Yet the documentation (http://www.gbif.org/developer/species#p_habitat) has not changed.

**Comment by sckott** [comment]
thanks for the report @willgearty - Looking into it now

**Comment by sckott** [comment]
@willgearty looks like they did indeed change to 3 values of habitat http://gbif.github.io/gbif-api/apidocs/org/gbif/api/vocabulary/Habitat.html

**Comment by willgearty** [comment]
Oh, I see. Seems like they are still rolling it out, or at least, they only have some taxa coded for freshwater.
No mammals are coded as freshwater yet, but it seems snails are:
http://api.gbif.org/v1/species/search?highertaxonKey=225&habitat=FRESHWATER

**Comment by sckott** [comment]
@willgearty Okay, try reinstalling from github: `devtools::install_github("ropensci/rgbif")` then try those egs again, they should work now. 

the `habitat` values now go into a single table cell, comma-separated

hmm, don't know much about the habitat field, the mailing list would be a good place to ask http://lists.gbif.org/mailman/listinfo/api-users

**Comment by willgearty** [comment]
I've reinstalled from github but I'm still getting X.TERRESTRIAL and X.MARINE instead of a single habitat cell.
```name_lookup(query="*", rank="species", higherTaxonKey=358,limit=1000,start=0)```

**Comment by sckott** [comment]
fixing that now

**Comment by sckott** [comment]
woops, didn't mean to close, okay, try again

**Comment by willgearty** [comment]
Seems to work great now! Thanks, Scott!

**Comment by sckott** [comment]
great! I've written some tests for the habitat parameter and returned field, so we'll catch it if they change it  again
